# Default values for moonbase.
# This is a YAML-formatted file.

replicaCount: 1

image:
  repository: moonbase
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 4343
  targetPort: 4343

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: moonbase.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: moonbase-tls
  #    hosts:
  #      - moonbase.local

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi
  storageClass: ""

config:
  logs:
    dir: "logs"
    level: "debug"
  api:
    port: 4343
    corsOrigin: "*"
  auth:
    authDbCid: "zdpuAwKvuPvsSgcD1vPN3MjhF8rEfnXzgGAXnTRn2DbQ9Shb8"
    sessionDbCid: "zdpuAtk34p4dSV2wCLEZPoiYCvdNii5XZ5i7h8USeocDGe229"
    eventLogCid: "zdpuB1gWhT3fdGv6CxJKh9y9gMTax9xajiC2ErumHgkH2Gi3E"
    systemSwarmKey: "deeaa20d10f8379c3ab1fc10f5c24fb1a5d1aeae9d9095cc12d91a95fe96409a"
