apiVersion: apps/v1
kind: Deployment
metadata:
  name: airlock
  labels:
    app: airlock
    version: v0.0.1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airlock
  template:
    metadata:
      labels:
        app: airlock
    spec:
      containers:
        - name: airlock
          image: "airlock:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 4343
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          env:
            - name: NODE_ENV
              value: "production"
