apiVersion: v1
kind: Service
metadata:
  name: airlock
  labels:
    app: airlock
spec:
  type: ClusterIP
  ports:
    - port: 4343
      targetPort: 4343
      protocol: TCP
      name: http
  selector:
    app: airlock
