# Default values for airlock.
replicaCount: 1

image:
  repository: airlock
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 4343
  targetPort: 4343

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
