apiVersion: v1
kind: Service
metadata:
  name: moonbase
  labels:
    app: moonbase
spec:
  type: ClusterIP
  ports:
    - port: 4343
      targetPort: 4343
      protocol: TCP
      name: http
  selector:
    app: moonbase
